const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  loadConfig: () => ipcRenderer.invoke('load-config'),
  saveConfig: (data, conflictBases) => ipcRenderer.invoke('save-config', data, conflictBases),
  importSyllabus: () => ipcRenderer.invoke('import-syllabus'),
  fetchTimetable: (identifier) => ipcRenderer.invoke('fetch-timetable', identifier),
  setOpacity: (v) => ipcRenderer.send('set-opacity', v),
  setAlwaysOnTop: (f) => ipcRenderer.send('set-always-on-top', f),
  close: () => ipcRenderer.send('close-app'),
  minimize: () => ipcRenderer.send('minimize-app'),
  notify: (title, body) => ipcRenderer.send('notify', { title, body }),
  lmsLogin: () => ipcRenderer.invoke('lms-login'),
  lmsStatus: () => ipcRenderer.invoke('lms-status'),
  lmsRefresh: () => ipcRenderer.invoke('lms-refresh'),
  lmsOpen: (url) => ipcRenderer.send('lms-open', url),
  lmsDump: () => ipcRenderer.invoke('lms-dump'),
  setMini: (on) => ipcRenderer.send('set-mini', on),
  getAutoStart: () => ipcRenderer.invoke('get-auto-start'),
  setAutoStart: (on) => ipcRenderer.invoke('set-auto-start', on),
  onSubmissionClosed: (cb) => ipcRenderer.on('lms-submission-closed', () => cb()),
  lmsDownload: (items) => ipcRenderer.invoke('lms-download', items),
  openStudeckFolder: (kind, course) => ipcRenderer.invoke('open-studeck-folder', { kind, course }),
  gitConnect: (repo, token) => ipcRenderer.invoke('git-connect', { repo, token }),
  gitSync: (resolution) => ipcRenderer.invoke('git-sync', resolution),
  onSyncStatus: cb => ipcRenderer.on('sync-status', (_e, status) => cb(status)),
  onRequestQuit: cb => ipcRenderer.on('request-quit', () => cb()),
  gitSyncStatus: () => ipcRenderer.invoke('git-sync-status'),
  gitDisconnect: () => ipcRenderer.invoke('git-disconnect'),
});
