// Isolated renderer integration. No real profile, credentials, files, or network.
const { app, BrowserWindow } = require('electron');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'study-sync-ui-'));
app.setPath('userData', temp);
const timeout = setTimeout(() => { console.error('Sync UI test timed out'); app.exit(1); }, 20000);
const preload = path.join(temp, 'preload.cjs');
fs.writeFileSync(preload, `window.test = { enabled:false, writes:[], closes:0, result:{ok:true,snapshot:{},status:{phase:'synced'}} };
window.api=new Proxy({}, {get:(_,key)=>{
  if(key==='loadConfig') return async()=>({lmsAuto:false,autoDownload:false,rolloverOverdue:false,assignFix1:true,materialsFix2:true});
  if(key==='saveConfig') return async(data,bases)=>{if(test.failSave)throw new Error('disk full');test.writes.push({data,bases});return data;};
  if(key==='gitSyncStatus') return async()=>({enabled:test.enabled});
  if(key==='gitSync') return async resolution=>{test.resolution=resolution;if(test.during)await test.during();return test.result;};
  if(key==='openStudeckFolder') return async(kind,course)=>{test.folder={kind,course};return {ok:true};};
  if(key==='close') return ()=>test.closes++;
  if(key==='onRequestQuit') return cb=>test.quit=cb;
  if(key==='onSyncStatus') return cb=>test.status=cb;
  return async()=>({enabled:false,ok:true});
}});`);
app.whenReady().then(async () => {
  const win = new BrowserWindow({ width: 320, height: 640, show: false, webPreferences: { preload, contextIsolation: false, sandbox: false, backgroundThrottling: false } });
  try {
    await win.loadFile(path.join(__dirname, '..', 'index.html'));
    const result = await win.webContents.executeJavaScript(`(async()=>{
      const check=(condition,message)=>{if(!condition)throw new Error(message)};
      const settle=()=>new Promise(r=>setTimeout(r,20));
      const until=async check=>{const start=Date.now();while(!check()){if(Date.now()-start>3000)throw new Error('UI transition timed out');await settle();}};
      await initSync();
      state.todos=[{id:'mini-parent',text:'Parent',subject:'오픈소스개발프로젝트 긴 과목명',due:todayStr(),done:false,subs:[{text:'Child',done:false}]}];
      toggleMini();
      const chip=$('mini-list').querySelector('.subj-chip');
      check(chip?.textContent===state.todos[0].subject&&getComputedStyle(chip).display!=='none','Mini course hidden');
      check(chip.getBoundingClientRect().right<=innerWidth&&document.documentElement.scrollWidth<=innerWidth,'Mini course overflows narrow window');
      let badge=$('mini-list').querySelector('[data-expand]');
      check(badge&&getComputedStyle(badge).display!=='none','Mini expand control hidden');
      badge.click();check(!!$('mini-list').querySelector('[data-subtoggle]'),'Mini child did not expand');
      $('mini-list').querySelector('[data-subtoggle]').click();await flushSaves();
      check(state.todos[0].subs[0].done,'Mini child completion not saved');
      $('mini-list').querySelector('[data-expand]').click();check(!$('mini-list').querySelector('[data-subtoggle]'),'Mini child did not collapse');
      openTodoMenu('todo','mini-parent',10,10);
      [...document.querySelectorAll('.popover .opt')].find(x=>x.textContent==='하위 항목 추가').click();
      check(document.activeElement===$('mini-list').querySelector('[data-subadd]'),'Mini context menu did not open child input');
      toggleMini();
      renderTimetable([{name:'Sample Course',professor:'',times:[{day:0,start:108,end:120,place:''}]}]);
      $('grid-wrap').querySelector('.block').click();
      check(test.folder?.kind==='subject'&&test.folder.course==='Sample Course','Timetable did not open course folder');
      await flushSaves();
      test.failSave=true; state.todos=[{id:'a',text:'offline task',done:false}]; persist({todos:state.todos}); await settle();
      check($('sync-label').textContent.includes('저장 실패'),'Save failure hidden');
      await requestQuit();check(test.closes===0,'Quit despite failed local save');
      test.failSave=false;await flushSaves();check(test.writes.some(w=>w.data.todos?.[0].text==='offline task'),'Failed save not retried');
      test.enabled=true;
      test.result={ok:false,error:'offline'};
      const quitting=requestQuit();await until(()=>!!$('sync-exit'));
      $('exit-stay').click();await quitting;check(test.closes===0,'Stay still closed');
      const offlineExit=requestQuit();await until(()=>!!$('sync-exit'));$('exit-offline').click();await offlineExit;check(test.closes===1,'Offline exit unavailable');
      test.closes=0;
      test.result={ok:true,snapshot:{todos:[{id:'a',text:'offline task',done:false},{id:'b',text:'remote added',done:false}]},status:{phase:'synced'}};
      test.during=async()=>{state.todos[0].text='edited during upload';persist({todos:state.todos});await flushSaves();};
      await initSync();test.during=null;await flushSaves();
      check(state.todos.length===2&&state.todos[0].text==='edited during upload','Concurrent local or incoming edits lost');
      check($('sync-label').textContent.includes('대기'),'Concurrent edits falsely called uploaded');
      const timetableConflict={id:'time-conflict',path:['timetableFull',{name:'Study'},'times'],base:{exists:true,value:[{day:0,start:108,end:120,place:'A'}]},local:{exists:true,value:[{day:1,start:120,end:132,place:'B'}]},remote:{exists:true,value:[{day:2,start:132,end:144,place:'C'}]}};
      showSyncStatus({phase:'conflict',conflicts:{kind:'settings',token:'time',items:[timetableConflict]}});$('sync-resolve').click();
      const compare=$('sync-conflicts').textContent;
      check(compare.includes('Study')&&compare.includes('변경 전')&&compare.includes('월 09:00–10:00 · A')&&compare.includes('화 10:00–11:00 · B')&&compare.includes('수 11:00–12:00 · C'),'Timetable comparison missing readable differences');
      $('sync-conflicts').remove();
      const item={id:'conflict',path:['todos',{id:'a'},'text'],local:{exists:true,value:'<script>local</script>'},remote:{exists:true,value:'remote'}};
      const conflicts={kind:'settings',token:'sample',items:[item]};
      showSyncStatus({phase:'conflict',conflicts});$('sync-resolve').click();
      check(!!$('sync-conflicts')&&!$('sync-conflicts').querySelector('script'),'Conflict dialog or escaping broken');
      const select=$('sync-conflicts').querySelector('select');select.value='remote';select.dispatchEvent(new Event('change'));
      test.result={ok:true,snapshot:{todos:[{id:'a',text:'chosen remote',done:false}]},status:{phase:'synced'}};
      $('sync-conflicts').querySelector('.primary').click();await until(()=>!$('sync-conflicts'));
      check(test.resolution.choices.conflict==='remote'&&!$('sync-conflicts'),'Choice not sent');
      check(state.todos[0].text==='chosen remote','Resolved state not applied');
      test.status({phase:'synced',lastSuccessfulAt:Date.now(),conflicts:null,error:''});
      check($('sync-label').textContent==='GitHub 업로드 완료','Status label incorrect');
      await test.quit();check(test.closes===1,'Native quit path did not flush and close');
      return 'PASS: mini subtasks expand/collapse/check/add, timetable course folder, failed-save retry/quit guard, offline-exit choices, concurrent edits, conflict dialog, escaped content and native quit callback';
    })()`);
    console.log(result);
    app.exit(0);
  } catch (error) { console.error(error); app.exit(1); }
});
app.on('will-quit', () => { clearTimeout(timeout); fs.rmSync(temp, { recursive: true, force: true }); });
